global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using NetCafe.Server.Models;
global using NetCafe.Server.Data;
global using NetCafe.Server.Exceptions;
global using NetCafe.Server.Options;
global using NetCafe.Shared.UserRequests;
global using NetCafe.Server.Repositories;
global using NetCafe.Shared.ApiResponses